#! /bin/sh
set -x #echo on

DESC="Auto wifi service"
NAME=nsweight
RUNDIR=/home/debian/bin/snowMan/
#DAEMON=/usr/sbin/$NAME
#DAEMON_ARGS=""
#PIDFILE=$RUNDIR/wicd.pid
SCRIPTNAME=/etc/init.d/$NAME
RUN_AS=root

### BEGIN INIT INFO
# Provides:          snowman
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 2 3 6
# Description:       Starts the snowman service
### END INIT INFO


# Some things that run always


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting SnowMan..."

    cd $RUNDIR
    ./runSnow.sh &
    ;;
  stop)
    echo "Stopping SnowMan..."
    sudo killall runSnow.sh
    ;;
  *)
    echo "Usage: /etc/init.d/snowman{start|stop}"
    exit 1
    ;;
esac
